### ISSUE TITLE
Improper header parsing resulting in incorrect 'Malformed SAM header line:' error message

### ISSUE THREAD

**Issue by adamstruck** [gt1/biobambam2#14]
The bamreset tool parses the header incorrectly. 

It complains that the @RG line is malformed if it is tab delimited. Whereas if @RG and the first value are separated by a tab and all other values are separated by a space the 'Malformed SAM header line" is not reported. 

Per the header section in https://samtools.github.io/hts-specs/SAMv1.pdf 

> In the header, each line is TAB-delimited and, apart from @CO lines, each data field follows a format ‘TAG:VALUE’ where TAG is a two-character string that defines the format and content of VALUE. Thus header lines match /^@[A-Z][A-Z](t[A-Za-z][A-Za-z0-9]:[ -~]+)+$/ or /^@CO\t.*/

**Comment by gt1** [comment]
Hi,

I am reasonably sure that the character used for tokenizing header lines is the tab (see https://github.com/gt1/libmaus2/blob/master/src/libmaus2/bambam/HeaderLine.hpp#L299 ). Could you please extract a minimal file and provide it? Something like

```
( samtools view -H c.bam | egrep "^@HD|^@RG" ; printf "@SQ\tSN:1\tLN:1\n" ) | samtools view -S -b - > header.bam
```

should create one. The resulting file only contains a header. You can view it using

```
samtools view -H header.bam
```

Please also check which characters are used for separating fields by something like

```
samtools view -H header.bam | egrep "^@RG" | hexdump -c
```

Best,
German

**Comment by adamstruck** [comment]
Apologies, I was adding an invalid field to my RG line.
