### ISSUE TITLE
bamdownsamplerandom - sort order issues with cram input

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#15]
Hi,

This gives warnings that the sort order is unknown on files where the field is appropriately set in the header:

```
$ samtools-1.2 view -H cram/MD5146a.cram | head -n 1
@HD VN:1.5  SO:coordinate
$ biobambam2-2.0.33-release-20160317091357-x86_64-etch-linux-gnu/bin/bamdownsamplerandom reference=/nfs/cancer_ref01/mouse/37/genome.fa p=0.1 filename=cram/MD5146a.cram inputformat=cram outputformat=cram O=ds.cram
Unknown sort order field: unknown
...
```

This doesn't occur for BAM input.

Regards,
Keiran

**Comment by gt1** [comment]
Hi Keiran,

this message originates from io_lib. Please create a ticket at https://sourceforge.net/p/staden/bugs/ to have this checked.

Best,
German

**Comment by keiranmraine** [comment]
Raised
