### ISSUE TITLE
bammerge - option for output file not documented

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#2]
bammerge has options to generate md5 and index filenames based on the output file name however this option is not documented in the man page or the `-h` option.

I've tried various values used in other steps that have this same option (O, outputfile, filename, file).

Having a look at the code I can't see anything that attempts to load any output filenames.

Also the option `IL` is not in the short help given by `-h`.

**Comment by gt1** [comment]
I have updated the help message to state that one needs to provide values for indexfilename/md5filename to get the respective output files. IL is now in the short help message.
