### ISSUE TITLE
bamcat syscall error

### ISSUE THREAD

**Issue by guillermo-carrasco** [gt1/biobambam2#20]
Hi,

When executing `bamcat` command I get the following message:

```
 login01 /scratch/gcarrasco/tests/test_bcbio_cwl ~> bamcat
libmaus2::util::PosixExecute::execute() donotthrow: "addr2line --exe=bamcat 0x4140a0" exited with status 1
libmaus2::util::PosixExecute::execute() donotthrow: failing command was addr2line --exe=bamcat 0x4140a0
libmaus2::util::PosixExecute::execute() donotthrow: failed syscall  login01
```

Besides that, the program seems to work. We're running Linux Centos 6.6 in our cluster and the package was installed via conda. 

Any clue of why this may be happening?

Thanks a lot in advance,

**Comment by gt1** [comment]
Hi,

error messages from biobambam2 are reported including a stack trace to show where they originate from. To make the stack trace more useful it tries to convert the addresses to function names using the addr2line program. This program seems to be missing on your system. The message can be safely ignored. The error produced by just calling bamcat without any arguments and stream redirections is that it refuses to produce a (binary) BAM file in a terminal.

Best,
German

**Comment by guillermo-carrasco** [comment]
Hi German, 

Thank you for your answer.

Both programs `bamcat` and `addr2line` seem to be correctly installed:

```
 login01 /scratch/gcarrasco/tests ~> which bamcat
/cm/shared/apps/bcbio/20150720-devel/tools/bin/bamcat

 login01 /scratch/gcarrasco/tests ~> which addr2line
/usr/bin/addr2line
```

However, trying to execute the `addr2line` command alone, I get this:

```
login01 /scratch/gcarrasco/tests ~> addr2line --exe=bamcat 0c4140a0
addr2line: 'bamcat': No such file
```

Adding the full path, I get what it seems to be a "correct" answer (not very readable though):

```
login01 /scratch/gcarrasco/tests ~> addr2line --exe=`which bamcat` 0c4140a0
??:0
```

Could that be the problem? 

Thanks again

**Comment by gt1** [comment]
Hi,

yes, that would explain it. I have disabled calling addr2line for non debug builds of libmaus2/biobambam2 and also implemented detection of the full binary path, so this error should disappear.

Best,
German

**Comment by guillermo-carrasco** [comment]
Thanks so much German!
