### ISSUE TITLE
Query: does bb2 support new bgzip fasta reference?

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#28]
I recently tried to convert a BAM to CRAM with scramble providing a bgzip compressed fasta file and index as generated by samtools 1.3+ and found it wasn't compatible.

Is this supported in biobambam2 or would this limitation carry over (from io_lib)?

**Comment by gt1** [comment]
biobambam2 relies on io_lib concerning pretty much everything relating to CRAM, so I would expect the limitation to carry over to biobambam2. Maybe James would like to add support for compressed reference files in io_lib.

**Comment by keiranmraine** [comment]
Currently in discussion, closing.
