### ISSUE TITLE
question about bamtofastq

### ISSUE THREAD

**Issue by hurleyLi** [gt1/biobambam2#3]
Really amazing tool kits!

I have an already name-sorted bam file with paired-end reads, and I want to convert it to fastq files. 
It seems that I have to specify collate=1, even though it's already collated by read name, or otherwise the results will be print out on screen (stdout) rather than writing to the files specified by F and F2.

I'm wondering in this case, what values should I pass to 'colhlog' and 'colsbs', in order to most efficiently convert the file, since it's an already name-sorted bam file.

Or can I specify collate=0 and still let the results output to F and F2 files?

Thanks!
Hurley

**Comment by gt1** [comment]
Output spliiting into F, F2 etc requires the collate machinery. With collate=0 the program does not even know whether a read is a first or second mate. When a file is pre collated then setting colhlog and colsbs to lower values may result in a minor speedup, but in my experience this effect is negligible.

Best,
German
