### ISSUE TITLE
Question - bammarkduplicates2 - does it invoke 'top'?

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#32]
Hi,

Just found a very odd log, which appears to include the output of top, that indicated a memory allocation error.

```
AutoArray<unsigned char,alloc_type_cxx> failed to allocate 268435456 elements (268435456 bytes)
current total allocation 306663325
```

Is biobambam invoking 'top' or do I need to raise this with our systems group?

Thanks

**Comment by gt1** [comment]
Hi Keiran,

it invokes top in case a memory allocation fails. I added this at some 
point to see whether there were other programs around taking too much 
memory in case an allocation fails.

Best,

German

**Comment by keiranmraine** [comment]
Okay, thanks
