### ISSUE TITLE
Empty MC:Z tags from bamsormadup in 2.0.57

### ISSUE THREAD

**Issue by chapmanb** [gt1/biobambam2#34]
German;
I'm running into the same issue as reported in #24 in the latest release and will get empty MC:Z tags from bamsormadup:
```
HWI-EAS264:7:101:6410:6415#0    121     chrM    389     60      76M     =       389     0       CAGATTTCAAATTTTATCTTTTGGCGGTATGCACTTTTAACAGTCACCCCCCAACTAACACATTATTTTCCCCTCC    BA?BABDBBDDBBBBDADCDDCDCBDCCCCCDCCCDDCCDCCC@@BCCCCCCCCCCCCCDCB@CCCCC@BCCCCCC    NM:i:1  MD:Z:21A54      AS:i:71 XS:i:0  RG:Z:Test1      ms:i:179        mc:i:388        MC:Z:
HWI-EAS264:7:101:6410:6415#0    181     chrM    389     0       *       =       389     0       GTTGGGGTTTTTGTTTTTGGGGGTTGGGAGGGGTGGGGTTAAGGGGTTGGGGCAGGAGGGGGGGGGGGGGGGGGGG    ######################################################################A=A==@    AS:i:0  XS:i:0  RG:Z:Test1      MQ:i:60 ms:i:2563       mc:i:464
```
I put together a small test case that demonstrates the problem:
```
wget http://s3.amazonaws.com/chapmanb/testcases/biobambam_empty_mc.tar.gz
```
Thanks so much for the help and let me know if I can provide any other information.

**Comment by gt1** [comment]
Hi Brad,

sorry for this. Could you try again with version 2.0.58?

Thanks
German

**Comment by chapmanb** [comment]
German -- thanks so much for looking at this so quickly. The updated version works great in my tests and fixes the issue I was running into. Thank you again.
