### ISSUE TITLE
Not working on Centos7 –libmaus2 related error

### ISSUE THREAD

**Issue by akhats** [gt1/biobambam2#42]
Hi there, I tried installing it with `conda install biobimbam` which install version 2.0.62-0. When I run bamtofastq in gives me this error which seems to be related to libmaus2 

> Unable to parse argument  as type std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
> 
> /root/miniconda2/share/biobambam-2.0.62-0/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x55)[0x7f6bda09bfd5]
> bamtofastq(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x41aec0]
> bamtofastq()[0x430655]
> bamtofastq()[0x4307a3]
> bamtofastq()[0x4173a9]
> bamtofastq()[0x4183a2]
> bamtofastq()[0x4121b5]
> /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f6bd7210b35]
> bamtofastq()[0x4133d2]
> 

I tried to compile it (version 2.0.70) with libmaus2 as described in README.md but it again throws similar looking error :

> Unable to parse argument  as type std::string
> 
> /arun/...../libmaus2/lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x54)[0x7f27d374e194]
> bamtofastq(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x436c80]
> bamtofastq(std::string libmaus2::util::ArgInfoParseBase::parseArg<std::string>(std::string const&)+0xea)[0x44ccda]
> bamtofastq(std::string libmaus2::util::ArgInfo::getValue<std::string>(std::string const&, std::string) const+0x43)[0x44ce13]
> bamtofastq(bamtofastqCollating(libmaus2::util::ArgInfo const&)+0x2a6)[0x4334d6]
> bamtofastq(bamtofastq(libmaus2::util::ArgInfo const&)+0x3bc)[0x4346ec]
> bamtofastq(main+0x16b3)[0x42e243]
> /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f27d1c12b35]
> bamtofastq()[0x42f73f]
>

**Comment by gt1** [comment]
Could you provide the command line you used?

**Comment by akhats** [comment]
I am trying to extract fastq files from one of the bam files of TCGA whole-exome dataset.  

- I initially tried the command they have mentioned on gdc [docs](https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline/).

```
bamtofastq \
collate=1 \
exclude=QCFAIL,SECONDARY,SUPPLEMENTARY \
filename= <input.bam> \
gz=1 \
inputformat=bam
level=5 \
outputperreadgroup=1 \
outputperreadgroupsuffixF=_1.fq.gz \
outputperreadgroupsuffixF2=_2.fq.gz \
outputperreadgroupsuffixO=_o1.fq.gz \
outputperreadgroupsuffixO2=_o2.fq.gz \
outputperreadgroupsuffixS=_s.fq.gz \
tryoq=1 \
```
- I also tried removing tryoq=1 and level=5 options.

**Comment by gt1** [comment]
Assuming you really do have a space after filename= then please retry 
without, i.e.

bamtofastq filename=in.bam

instead of

bamtofastq filename= in.bam

**Comment by akhats** [comment]
Ohh, the space!!
Thanks 👍 It works now.
