### ISSUE TITLE
Conflicting executable names

### ISSUE THREAD

**Issue by sjackman** [gt1/biobambam2#44]
Biobambam2's `bamtofastq` conflicts with Bedtool's `bamToFastq` and
Biobambam2's `fastaexplode` conflicts with Exonerate's `fastaexplode`.
You may want to consider renaming these two tools. Adding a prefix to the tool names, such as `biobambam-fastaexplode` is a good way to avoid collisions.

**Comment by gt1** [comment]
I think this is more of a packaging issue. This project exists for long enough that just renaming any of the programs at this stage is likely to be confusing people who are already using it.

**Comment by sjackman** [comment]
Hi, German. I'm packaging biobambam2 for Homebrew-Science. I plan to rename the two executables to `biobambam-bamtofastq` and `biobambam-fastaexplode`, unless you have an alternative suggestion.

**Comment by mmokrejs** [comment]
Hi German, I also propose renaming the binaries in a same way (a Gentoo package creator). Currently we have: https://cgit.gentoo.org/proj/sci.git/commit/?id=51fe11a3b2a3519a325f9cb86f1b27ea0cf9ec62

**Comment by gt1** [comment]
Hi,

I would suggest to use configure's option --program-prefix to set a different prefix for the binaries.

Best,
German

**Comment by sjackman** [comment]
For compatibility between distributions, it's best if we agree on the same solution.
@mmokrejs Shall we set `--program-prefix=biobambam` to set the prefix of all executables, or rename only those two executables with known conflicts, `bamtofastq` and `fastaexplode`?

**Comment by mmokrejs** [comment]
I would rename just the two but I would add suffix, so `bamtofastq_biobambam2` and `fastaexplode_biobambam2`. It is easier to locate the renamed binary in shel via `bamtofastq` and pressing `TAB` twice. ;-)

**Comment by sjackman** [comment]
I prefer hyphens to underscores. Easier to see and no shift required when typing. How about
`bamtofastq-biobambam2` and `fastaexplode-biobambam2`
Include or omit the `2` suffix?
