### ISSUE TITLE
bamcollate2 - segfaults

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#47]
Under v2.0.54 (pre-compiled binaries) we've seen some segfaults occurring yet they when they reoccur they seems to be at different points in the input BAM.

I've had a look at the changes and commit info and I can't see any specific items relating to issues in bamtofastq.

There's didn't seem to be any error message however the output stream was bing consumed by a wrapper which may have 'hidden' it somehow.  Information pulled by our admins:

> May 18 12:04:42 cgp-7-1-16 kernel: [4226734.618114] show_signal_msg: 9 callbacks suppressed
> May 18 12:04:42 cgp-7-1-16 kernel: [4226734.618121] bamcollate2[25298]: segfault at 1 ip 0000000000000001 sp 00007ffd10f74478 error 14 in bamcollate2[400000+b9000]
> May 18 12:04:42 cgp-7-1-16 kernel: [4226734.621187] bamcollate2[25461]: segfault at 1 ip 0000000000000001 sp 00007ffd7f499e78 error 14 in bamcollate2[400000+b9000]
> May 18 12:04:42 cgp-7-1-16 kernel: [4226734.627157] bamcollate2[25454]: segfault at 1 ip 0000000000000001 sp 00007ffc742608f8 error 14 in bamcollate2[400000+b9000]
> May 18 12:04:42 cgp-7-1-16 kernel: [4226734.627372] bamcollate2[25297]: segfault at 1 ip 0000000000000001 sp 00007ffe856a91f8 error 14 in bamcollate2[400000+b9000]
>  
> The first message indicates nine similar messages were also logged, so there were quite a few of these in quick succession.  I can't see any indication of a hardware fault on cgp-7-1-16, so it may be a rare bug in the software or possibly a kernel issue.

I'm retrying with the latest binaries (2.0.72) on `Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-105-generic x86_64)`.  Is it safe to use the etch binaries like this?

**Comment by gt1** [comment]
The 2.0.72 binaries should be ok. Please let me know, if this is reproducible on another machine.

**Comment by keiranmraine** [comment]
Seems to be something transient on the cluster.  Closing as I can't give any useful information.
