### ISSUE TITLE
Installation Error. "programs/bamadapterfind.cpp: using ‘typename’ outside of template"

### ISSUE THREAD

**Issue by yuankunzhu** [gt1/biobambam2#53]
Successfully installed [libmaus2](https://github.com/gt1/libmaus2), and had also successfully installed biobambam2 in other OS, but always got error below when `make install` in CentOS 6.8

```
...
programs/bamadapterfind.cpp:143: error: using ‘typename’ outside of template
programs/bamadapterfind.cpp:144: error: using ‘typename’ outside of template
make[1]: *** [programs/bamadapterfind-bamadapterfind.o] Error 1
...
```

**Comment by gt1** [comment]
I have removed the offending typename keywords in https://github.com/gt1/biobambam2/commit/c2d1a80a4dc40f351dea77e3cd2e7863ab58ed4b#diff-484e4673a5a53a831b6c409d261546dc . Could you retry with the latest release?

**Comment by yuankunzhu** [comment]
It works well now. Thanks!
