### ISSUE TITLE
bamtofastq - output ordering

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#57]
Is there are any guarantee that a non-paired read will not be output between 2 reads of a pair when F, F2 and S are all to the same file/pipe?

I'm looking to have a piped process digest collated fastq data but I also want to be able to accept any reads that may be single-end (flag bit 1 not set).  Knowing that these will not be output between reads of a pair would be helpful.

Thanks

**Comment by gt1** [comment]
Hi Keiran,

a pair appearing consecutively in a file containing F and F2 only will also appear consecutively in F, F2, S. Make sure to exclude supplementary/secondary lines though for this purpose, they may produce some strange effects.

Hope this helps
German

**Comment by keiranmraine** [comment]
Thanks.
