### ISSUE TITLE
bamsort - multiple unsorted SAM input fails when no records

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#6]
If you have a set of SAM files as input for bamsort where all have no actual reads it fails.  One file like this causes no issue but adding additional files causes a failure:

```
$ grep -cv '^\@' 1_pindel_wt.sam
0
$ bamsort inputformat=sam O=test.bam I=1_pindel_wt.sam
[V] Reading alignments from source.
[V] read 0 alignments
[V] producing sorted output
[V] wrote 0 alignments
$ grep -cv '^\@' 2_pindel_wt.sam
0
$ bamsort inputformat=sam O=test.bam I=1_pindel_wt.sam I=2_pindel_wt.sam
BamMergeTemplate::BamMergeTemplate(): cannot merge, not all files are marked as sorted.

/software/CGP/external-apps/biobambam2-2.0.18/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x4c)[0x7f08b5d0d33c:??:0]
/software/CGP/external-apps/biobambam2/bin/bamsort(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x418390:??:0]
/software/CGP/external-apps/biobambam2/bin/bamsort()[0x476d57:??:0]
/software/CGP/external-apps/biobambam2/bin/bamsort()[0x48f37e:??:0]
/software/CGP/external-apps/biobambam2/bin/bamsort()[0x48f8ec:??:0]
/software/CGP/external-apps/biobambam2/bin/bamsort()[0x4111c0:??:0]
/software/CGP/external-apps/biobambam2/bin/bamsort()[0x40d9a6:??:0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7f08b313376d:??:0]
/software/CGP/external-apps/biobambam2/bin/bamsort()[0x40e692:??:0]
```

Works fine for multiple unsorted SAM files when records are present.

**Comment by gt1** [comment]
Hi Keiran,

bamsort (like all the other biobambam2 tools allowing multiple instances of the I key) merges input files by coordinate, which I guess is not too useful for any application. Is the purpose of calling it with multiple input files to get a single coordinate sorted output file from unsorted input files?

Best,
German

**Comment by keiranmraine** [comment]
Hi German,

It works fine if I give it multiple unsorted files which contain reads, generating the expected single output file.  The problem is that for some datasets the general workflow can result in a set of SAM files with headers that contain no actual reads.

I can work round it by adding a header rewrite when this occurs:

```
perl -pi -e 's/SO:unsorted/SO:coordinate/g;' X.sam
```

I just thought it was something that should be highlighted.

Regards,
Keiran

**Comment by gt1** [comment]
I have changed the behaviour of bamsort when given multiple input files. Could you please check whether this works for you?

Thanks
German

**Comment by keiranmraine** [comment]
Hi German, this is now functional.

**Comment by gt1** [comment]
Thanks for checking.
