### ISSUE TITLE
bammaskflags - add condition option?

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#63]
Would it be possible to add a condition for masking a flag?

I'd like to be able to do something like:

```
bammaskflag maskneg=512 auxexists='mm'
```

or

```
bammaskflag maskneg=512 auxmatch='mm:A:Y'
```

The output would be the complete input BAM but with all reads having mm:A:Y having the flag 512 (QCFAIL) reset.  Assuming the aux tag test is only applied to reads matching the flags being reset it should be reasonably efficient (for the volume of reads we are looking at anyway).

I don't actually care about the value but others may for their use cases.

**Comment by gt1** [comment]
I have added the first version (without checking the content of the aux field) in bammaskflags. Please let me know whether this works for you.

**Comment by keiranmraine** [comment]
Thanks, works as expected.
