### ISSUE TITLE
csi indexing of BAM file

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#65]
BAM files can be indexed as `bai` or `csi`.  Will `bamsort` generate a valid csi index if `indexfilename=file.bam.csi`?

**Comment by gt1** [comment]
Hi Keiran,

I have added this in the latest version. Could you please let me know if this works for you?

Thanks
German

**Comment by keiranmraine** [comment]
Yes it works as expected, thanks

**Comment by gt1** [comment]
Thanks for checking.
