### ISSUE TITLE
does bamtofastq have same outputs for queryname and coordinate sorted input BAM/CRAM

### ISSUE THREAD

**Issue by djomlaart** [gt1/biobambam2#76]
Hi,
is biobambam bamtofastq aware how input is sorted? Does it keep track of read pairs (same as Picard) or it just outputs the read as soon as it comes to it (like Samtools)?

Should I queryname sort my BAM/CRAM prior to bamtofastq in order to get paired reads in my FASTQ outputs?

**Comment by gt1** [comment]
bamtofastq collates reads by name by default, so sorting an input file by query name is not necessary.

**Comment by djomlaart** [comment]
Thanks!
