### ISSUE TITLE
`bamsormadup` stalls if temp folder does not exist

### ISSUE THREAD

**Issue by fgvieira** [gt1/biobambam2#79]
Hi,

found this issue when some of my `bamsormadup` runs would not finish.

I'd define a temp file (e.g. `temp/run1/sample1.tmp`) but, when some part of the path does not exist (e.g. `/temp/run1` folder does not exist), it just stalls. I think it would be nice if it could print an error or just create all needed (sub-)folders.

cheers,

**Comment by gt1** [comment]
Hi,

could you try

https://gitlab.com/german.tischler/biobambam2/tags/2.0.93-release-20190312162502

using

https://gitlab.com/german.tischler/libmaus2/tags/2.0.603-release-20190312152702

?

**Comment by jmarshall** [comment]
@gt1: Does this mean biobambam2/libmaus2 development has moved to GitLab? If so, a note in _README.md_ and/or in the project description at the top of <https://github.com/gt1/biobambam2> would be useful.

**Comment by gt1** [comment]
@jmarshall: yes. I have added a note.

**Comment by fgvieira** [comment]
seems to work!
thanks
