### ISSUE TITLE
curl in binary release

### ISSUE THREAD

**Issue by keiranmraine** [gt1/biobambam2#9]
Hi,

The bin folder of the release includes 'curl'  I've found that this doesn't function for SSL connections resulting in having to ensure it is not included in installs.

Is there an actual need for the curl binary in the final bin?

Thanks

**Comment by gt1** [comment]
Hi,

I think the curl binary is fine, however the installation comes without a pre installed cert bundle. And as the installation is relocatable there is not really a way to add one to the package. You can set the path of a cert bundle in an env variable or as a curl option and the binary should work fine. None of the biobambam2 binaries uses the curl front end program though.

German

**Comment by keiranmraine** [comment]
Thanks for confirming
